FROM python:3.9-slim-bullseye

WORKDIR /app
COPY . /app

# Instalar requirements si los tienes
RUN pip install --no-cache-dir -r requirements.txt || true

# Render pasa el puerto en $PORT
ENV PORT=$PORT

EXPOSE $PORT

# Arrancar el bot
CMD ["python", "run_rasa.py"]