FROM python:3.9-slim-bullseye

WORKDIR /app
COPY actions /app/actions

RUN pip install --no-cache-dir -r actions/requirements.txt || true

EXPOSE 5055

CMD ["rasa", "run", "actions", "--port", "5055"]