FROM python:3.9-slim-bullseye

WORKDIR /app

COPY . /app
USER root

RUN pip install --upgrade pip
RUN pip install rasa==3.6.21
RUN pip install -r requirements.txt

# Render pasa el puerto en $PORT
EXPOSE 10000

# Arrancar Rasa con el puerto de Render
CMD ["python", "run_rasa.py"]
